version: "3.8"

services:
  frontend:
    container_name: ctims-web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: "dAbxJF2DRzqwGYn+BWKdj8o9ieMri4FWsmIRn77r2F8="
      REACT_APP_API_URL: "http://localhost:3333/api"
      NEXTAUTH_URL: "http://localhost:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    networks:
        - my-network

  backend:
    container_name: ctims-api
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    environment:
      DATABASE_URL: mysql://ctims:ctims@database:3306/ctims
    ports:
      - "3333:3333"
    restart: on-failure
    networks:
        - my-network

  database:
    container_name: ctims-db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    restart: on-failure
    networks:
        - my-network
networks:
    my-network:

