---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thischart.fullname" . }}
  labels:
{{ include "thischart.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thischart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "thischart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.docker.image }}:{{ .Values.git.ref }}"
          name: ctimsweb
          ports:
            - containerPort: {{ .Values.ctimsweb.port }}
              name: ctimsweb
      imagePullSecrets:
        - name: regcred
