apiVersion: v1
kind: Service
metadata:
  name: {{ include "thischart.fullname" . }}
  labels:
{{ include "thischart.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ctimsweb.port }}
      targetPort: {{ .Values.ctimsweb.port }}
  selector:
    app.kubernetes.io/name: {{ include "thischart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
